### ISSUE TITLE
[BUG] Ubuntu Github Action fails to login to GitHub package registry after updating to NPM 7.6.1

### ISSUE THREAD

**Issue by snebjorn** [npm/cli#2841]
### Current Behavior:
After I updated the NPM version by running `sudo npm install -g npm@latest` in my GH action I started getting a login error.
I found a few issues related to login issues with NPM 7 but they're all for prior versions to NPM@7.6.1 and they claim to be fixed.

The setup was working before updating NPM.

Error output:
```
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR! 
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login
```
My GH action config. I left in the caching part. But I don't suspect it of being the issue.
```yml
jobs:  
  dependencies:
    runs-on: ubuntu-latest
    name: Install Dependencies
    steps:
      - uses: actions/checkout@master
      - name: download dependencies from cache
        uses: actions/cache@v2
        id: node_cache
        with:
          path: |
            ~/.npm
            frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.MY_TOKEN }}" > ~/.npmrc
      - name: install
        if: steps.node_cache.outputs.cache-hit != 'true'
        run: |
          sudo npm install -g npm@latest
          npm --prefix frontend ci
```

### Expected Behavior:
It was working for NPM v6 so it was expected to work for NPM v7 also.

### Steps To Reproduce:
1. Update npm from 6 to 7  in your GH action by running `sudo npm install -g npm@latest`
2. Use an npm package from your own GitHub package registry
3. Run `npm ci`, not sure if the `--prefix` parameter is part of the problem
4. See error...

### Environment:
- GitHub Action environment: 2.277.1 https://github.com/actions/virtual-environments/blob/ubuntu18/20210302.0/images/linux/Ubuntu1804-README.md
- OS: Ubuntu 18.04.5
- Node: 14.16.0
- npm: 7.6.1

##### npm 6
<details>

```ini
; cli configs
long = true
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.14.11 node/v14.16.0 linux x64 ci/github-actions"

; default values
access = null
allow-same-version = false
also = null
always-auth = false
audit = true
audit-level = "low"
auth-type = "legacy"
before = null
bin-links = true
browser = null
ca = null
cache = "/home/runner/.npm"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
cidr = null
color = true
commit-hooks = true
depth = null
description = true
dev = false
dry-run = false
editor = "vi"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
format-package-lock = true
fund = true
git = "git"
git-tag-version = true
global = false
global-style = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
save-prod = false
scope = ""
script-shell = null
scripts-prepend-node-path = "warn-only"
searchexclude = null
searchlimit = 20
searchopts = ""
searchstaleness = 900
send-metrics = false
shell = "bash"
shrinkwrap = true
sign-git-commit = false
sign-git-tag = false
sso-poll-frequency = 500
sso-type = "oauth"
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
timing = false
tmp = "/tmp"
umask = 18
unicode = true
unsafe-perm = true
update-notifier = true
usage = false
user = 0
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch} {ci}" (overridden)
userconfig = "/home/runner/.npmrc"
version = false
versions = false
viewer = "man"
```
</details>

##### npm 7
<details>

```ini
_auth = (protected) 
access = null 
all = false 
allow-same-version = false 
also = null 
always-auth = false 
audit = true 
audit-level = null 
auth-type = "legacy" 
before = null 
bin-links = true 
browser = null 
ca = null 
cache = "/home/runner/.npm" 
cache-lock-retries = 10 
cache-lock-stale = 60000 
cache-lock-wait = 10000 
cache-max = null 
cache-min = 10 
cafile = null 
call = "" 
cert = null 
ci-name = "github-actions" 
cidr = null 
color = true 
commit-hooks = true 
depth = null 
description = true 
dev = false 
diff = [] 
diff-dst-prefix = "" 
diff-ignore-all-space = false 
diff-name-only = false 
diff-no-prefix = false 
diff-src-prefix = "" 
diff-text = false 
diff-unified = null 
dry-run = false 
editor = "vi" 
engine-strict = false 
fetch-retries = 2 
fetch-retry-factor = 10 
fetch-retry-maxtimeout = 60000 
fetch-retry-mintimeout = 10000 

; "user" config from /home/runner/.npmrc

//npm.pkg.github.com/:_authToken = (protected) 

; "cli" config from command line options

long = true 
omit = [] 
user-agent = "npm/7.6.1 node/v14.16.0 linux x64 ci/github-actions"
```
</details>
