### ISSUE TITLE
[QUESTION] npm version from-git fails in GitHub Actions workflow

### ISSUE THREAD

**Issue by yukipastelcat** [npm/cli#760]
# What / Why
`npm version from-git` fails with following GitHub Actions job:

```yaml
publish-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build-storybook
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup git
        run: |
            git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git config --global user.name "$GITHUB_ACTOR"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - name: Pull changes
        run: git pull
      - name: Bump version
        run: npm version from-git
```

Logs:
```
Run npm version from-git
  npm version from-git
  shell: /bin/bash -e {0}
npm ERR! code 128
npm ERR! Command failed: git describe --abbrev=0
npm ERR! fatal: No annotated tags can describe 'cd17592f7dc97aef27104191dab18e1c26a2023a'.
npm ERR! However, there were unannotated tags: try --tags.
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-02-03T14_21_04_846Z-debug.log
```
## Where
* https://github.com/yukipastelcat/svelte-fontawesome

However it works perfectly fine in [other repository](https://github.com/yukipastelcat/chronometric).

Workflows are almost identical and I don't understand what's wrong with my repository - error message just doesn't make sense, since this commit is tagged with 1.0.0. How can I resolve this problem?
