### ISSUE TITLE
[BUG] `npm publish --provenance` The default value `public` isn't used

### ISSUE THREAD

**Issue by regseb** [npm/cli#7706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
$ npm publish --provenance
...
npm notice Publishing to https://registry.npmjs.org/ with tag latest and default access
npm error code EUSAGE
npm error Can't generate provenance for new or private package, you must set `access` to public.
```

### Expected Behavior

npm should use the default value `public` ([`npm-publish --access`](https://docs.npmjs.com/cli/v10/commands/npm-publish#access)) when publish a new package.

### Steps To Reproduce

```yaml
name: Release
on:
  push:
    branches: [main]

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node

      # Si la release a été créée : publier le paquet dans npm.
      - name: Checkout repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Setup Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci

      - name: Publish in npm
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

### Environment

- npm: 10.8.1
- Node.js: v20.16.0
- OS Name: Ubuntu 22.04.4 LTS
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```
