### ISSUE TITLE
[QUESTION] Automate log in with auth token ?

### ISSUE THREAD

**Issue by DrakaSAN** [npm/cli#790]
# What / Why
I want to automate publishing package on npm (public registry) from my Gitlab CI.
I thought the [authentication token](https://docs.npmjs.com/about-authentication-tokens) would be the way to go.
After research (since the doc currently do not tell how the token are supposed to be used), it look like the standard use is to write them to `~/.npmrc`, and wait for npm to pick it up.
However this does not work in gitlab-ci jobs.

Example job illustrating the problem:

```yaml
stages:
  - npm

npm:
  image: node:lts-alpine
  stage: npm
  script:
    - echo "always_auth=true" >> ~/.npmrc
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
    - npm whoami
```

The question is: What is the expected / supported / official way to use authentication token ? Is it guaranteed to work in any platform ?

## Where

  * npm public registry
