### ISSUE TITLE
[BUG] Provenance URL normalization breaks GitHub Actions check

### ISSUE THREAD

**Issue by Llorx** [npm/cli#7978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Simply when I publish a package from GitHub Actions with
```
npm publish --provenance --access public
```
It fais with this error:
```
Error verifying sigstore provenance bundle: Failed to validate repository information: package.json: "repository.url" is "git+https://github.com/llorx/arrange-act-assert.git", expected to match "https://github.com/Llorx/arrange-act-assert" from provenance
```
If I try to change the repository url to "https://github.com/Llorx/arrange-act-assert", npm warns that the URL is normalized to "git+https://github.com/llorx/arrange-act-assert.git", so is impossible for me to publish a package.

### Expected Behavior

To not modify the repository URL so it can match the provenance URL.

### Steps To Reproduce

Having this GH Action:
```yml
name: Release

on:
  push:

jobs:
  publish-npmjs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```
And this package.json
```json
{
  "name": "arrange-act-assert-publish-test",
  "version": "0.0.1",
  "scripts": {
    "publish": "npm ci && npm run build && npm publish --provenance --access public"
  },
  "repository": {
    "url": "https://github.com/llorx/arrange-act-assert"
  }
  [...] // Remaining non-relevant options
}
```
When you run the action in GH, it fails with the error stated above.

### Environment

- npm: 10 (latest from setup-node => node-version: 22.x)
- Node.js: 22 (latest from setup-node => node-version: 22.x)
- OS Name: ubuntu 24
