### ISSUE TITLE
npm ci is ignoring commit hash - package is not updated

### ISSUE THREAD

**Issue by Blackbam** [npm/cli#980]
`npm ci `should take commit hashes with git packages into account.

Sample package.json snippet:

```
{
  "dependencies": {
    "my-custom-package": "git+https://oauth2:my_key@gitlab.example.com/my-project/my-common-project-package#4405b6d781a5fd4239d17b418a6d38cd687c6017"
  }
}
```

Sample gitlab-ci.yml:

```
build-js:
  image: node
  stage: build-js
  allow_failure: false
  before_script:
    - echo "STARTED > build-js"
    - cat project/.env
    - npm install -g grunt-cli
  script:
    - cd project
    - npm ci
    - grunt update-libraries
    - grunt
    - rm -rf node_modules
```

npm ci is not updating "my-custom-package" if it has already been running previously. Essentially it is ignoring the commit hash. npm ci should understand when the commit hash has changed in the package.json and download the adequate commit of the package. 

This only happens with npm ci. npm i and npm update are understanding this. If I go wrong somewhere be free to tell me :-)
